# Railway Configuration - Optimized for Spring Boot
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 30

[deploy.environmentVariables]
# JVM optimizations for Railway's 512MB limit
JAVA_OPTS = "-Xmx400m -Xms200m -XX:+UseSerialGC -XX:MaxRAMPercentage=75"
# Spring Boot optimizations
SPRING_PROFILES_ACTIVE = "railway"
# Maven build optimizations
MAVEN_OPTS = "-Xmx512m -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
