# Railway Configuration - Using pre-built JAR (no Maven build)
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prebuilt"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 30
startCommand = "java -Xmx400m -Xms200m -XX:+UseSerialGC -XX:MaxRAMPercentage=75 -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=railway -jar app.jar"

[deploy.environmentVariables]
# JVM optimizations for Railway's 512MB limit
JAVA_OPTS = "-Xmx400m -Xms200m -XX:+UseSerialGC -XX:MaxRAMPercentage=75"
# Spring Boot optimizations
SPRING_PROFILES_ACTIVE = "railway"
# Maven build optimizations
MAVEN_OPTS = "-Xmx512m -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
# Disable Railway's auto database configuration
SPRING_CLOUD_GCP_SQL_ENABLED = "false"
SPRING_CLOUD_CONFIG_ENABLED = "false"
# Disable automatic database injection
RAILWAY_DATABASE_AUTO_INJECT = "false"
