# Railway Configuration
$schema: https://railway.app/railway.schema.json
version: 2

build:
  builder: DOCKERFILE
  dockerfilePath: Dockerfile

deploy:
  numReplicas: 1
  sleepApplication: false
  restartPolicyType: ALWAYS

variables:
  # Environment variables for Railway
  RAILWAY_STATIC_URL: https://${{RAILWAY_PUBLIC_DOMAIN}}
  JAVA_OPTS: -Xmx512m -Xms256m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
